name: Build binaries

on:
  workflow_dispatch
  # schedule:
  #   - cron: '5 5 * * *'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINWALK_ROOT_DIR: /tmp/binwalk3
  BINWALK_BIN_NAME: binwalk3
  BINWALK_REPO: https://github.com/ReFirmLabs/binwalk.git
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0
  CHOCO: choco install -y -r --no-progress

defaults:
  run:
    shell: bash

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      BINWALK_PREBUILT_LATEST_TAG: ${{ steps.release_latest_tag.outputs.BINWALK_PREBUILT_LATEST_TAG }}
      BINWALK_CURRENT_COMMIT_ID: ${{ steps.release_commit_id.outputs.BINWALK_CURRENT_COMMIT_ID }}
      BINWALK_VERSION: ${{ steps.release_version.outputs.BINWALK_VERSION }}

    steps:
      - name: Get latest release tag of this repo
        id: release_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/
          BINWALK_PREBUILT_LATEST_TAG=$(gh release list -R mycodedoesnotcompile2/binwalk3_prebuilt_binary --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "BINWALK_PREBUILT_LATEST_TAG=$BINWALK_PREBUILT_LATEST_TAG" >> $GITHUB_OUTPUT
          echo "BINWALK_PREBUILT_LATEST_TAG=$BINWALK_PREBUILT_LATEST_TAG" >> $GITHUB_ENV

      - name: Clone binwalk repo and check if there is a new and uncompiled yet version
        id: release_commit_id
        run: |
          cd /tmp/
          git clone --depth=1 "$BINWALK_REPO" binwalk3

          cd "$BINWALK_ROOT_DIR"
          BINWALK_CURRENT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "BINWALK_CURRENT_COMMIT_ID=$BINWALK_CURRENT_COMMIT_ID" >> $GITHUB_OUTPUT

          # case: no new commit => abort the workflow
          if [[ $BINWALK_PREBUILT_LATEST_TAG == $BINWALK_CURRENT_COMMIT_ID ]]; then
            echo "[!] No new version to compile"
            exit 100
          fi

      - name: Get binwalk3 version
        id: release_version_cargo_get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.version
          options: --entry "$BINWALK_ROOT_DIR/Cargo.toml"

      - name: Set BINWALK_VERSION build variable
        id: release_version
        run: |
          BINWALK_VERSION=${{ steps.release_version_cargo_get.outputs.metadata }}
          echo "BINWALK_VERSION=$BINWALK_VERSION" >> $GITHUB_OUTPUT


##############

  build:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
          
          - TARGET: aarch64-unknown-linux-musl
            OS: ubuntu-24.04-arm
            
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-24.04-arm
          
          - TARGET: aarch64-apple-darwin
            OS: macos-latest

          - TARGET: x86_64-apple-darwin
            OS: macos-26-intel
          
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            
          - TARGET: x86_64-pc-windows-gnu
            OS: windows-latest
            
          - TARGET: aarch64-pc-windows-msvc
            OS: windows-11-arm
          # ------------------------------

          # disabling all cross targets as there is a bug which provokes never-ending task
          # - TARGET: x86_64-unknown-freebsd
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross

          # - TARGET: x86_64-unknown-netbsd
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross
            
          - TARGET: riscv64gc-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-riscv64-linux-gnu

          # - TARGET: riscv64gc-unknown-linux-musl
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross
            
          - TARGET: powerpc64-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-powerpc64-linux-gnu g++-powerpc64-linux-gnu
            
          - TARGET: powerpc64le-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu
           
          # - TARGET: aarch64-linux-android
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross
            
          - TARGET: mips64el-unknown-linux-gnuabi64
            OS: ubuntu-latest
            CC_PKG: gcc-mips64el-linux-gnuabi64 g++-mips64el-linux-gnuabi64
           
          # - TARGET: mips64el-unknown-linux-muslabi64
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross

          - TARGET: mips64-unknown-linux-gnuabi64
            OS: ubuntu-latest
            CC_PKG: gcc-mips64-linux-gnuabi64 g++-mips64-linux-gnuabi64
           
          # - TARGET: mips64-unknown-linux-muslabi64
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross
          
          - TARGET: loongarch64-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-14-loongarch64-linux-gnu g++-14-loongarch64-linux-gnu

          # - TARGET: loongarch64-unknown-linux-musl
          #   OS: ubuntu-latest
          #   CC_COMPILER: cross
            
    runs-on: ${{ matrix.OS }}

    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      CONTAINER: ${{ matrix.CONTAINER }}
      CC_PKG: ${{ matrix.CC_PKG }}
      CC_COMPILER: ${{ matrix.CC_COMPILER }}
      CROSS_CONFIG: /tmp/cross.toml
      
      BINWALK_PREBUILT_LATEST_TAG: ${{ needs.checkout.outputs.BINWALK_PREBUILT_LATEST_TAG }}
      BINWALK_VERSION: ${{ needs.checkout.outputs.BINWALK_VERSION }}

    steps:
      - name: Clone binwalk3 repo
        run: |
          cd /tmp/
          git clone --depth=1 "$BINWALK_REPO" binwalk3
      
      - name: Install and configure dependencies
        run: |
          if [[ $OS == windows* ]]; then
            $CHOCO wget
          fi
          
          if [[ $OS == ubuntu* ]]; then
            $APT update
            $APT install libfontconfig1-dev liblzma-dev
          fi

          # for musl builds
          if [[ $TARGET == *"-musl"* ]]; then
            $APT install musl-tools
          fi

          # for everything else
          if [[ -n "${CC_PKG:-}" ]]; then
            $APT install $CC_PKG
          fi

          # for arm targets
          if [[ $TARGET == "arm"* ]]; then
            cd "$BINWALK_ROOT_DIR"
            cargo install --force --locked bindgen-cli
          fi

          cargo install cross
          
          wget -nv "https://github.com/mycodedoesnotcompile2/rust_compile_config_files/raw/refs/heads/main/cross.toml" -O "$CROSS_CONFIG"
          wget -nv "https://github.com/mycodedoesnotcompile2/rust_compile_config_files/raw/refs/heads/main/config.toml" -O ~/.cargo/config.toml
          
      
      - name: Install rust target
        run: |
          if [[ $TARGET == "mips"* ]]; then
            rustup toolchain install nightly
            rustup component add rust-src --toolchain nightly
          else
            rustup target add $TARGET
          fi
        
      - name: Run build
        run: |
          cd $BINWALK_ROOT_DIR
          
          if [[ -z "${CC_COMPILER:-}" ]]; then
            CC_COMPILER="cargo"
          fi
          
          if [[ $TARGET == "mips"* ]]; then
            $CC_COMPILER +nightly build -Z build-std=std,panic_abort -p binwalk --release --target $TARGET
          else
            $CC_COMPILER build -p binwalk --release --target $TARGET
          fi
      
      - name: List build information
        run: |
          OLD_BINWALK_BIN_DIR="$BINWALK_ROOT_DIR/target/$TARGET/release"
          OLD_BINWALK_BIN_PATH="$OLD_BINWALK_BIN_DIR/binwalk"
          ls -alh "$OLD_BINWALK_BIN_DIR"
          if [[ $TARGET == *-windows-* ]]; then
            OLD_BINWALK_BIN_PATH="$OLD_BINWALK_BIN_DIR/binwalk.exe"
          fi

          BINWALK_BIN_PATH="${{ runner.temp }}/$BINWALK_BIN_NAME-$BINWALK_VERSION-$TARGET"
          if [[ $OS == windows* || $TARGET == *-windows-* ]]; then
            BINWALK_BIN_PATH="${{ runner.temp }}/$BINWALK_BIN_NAME-$BINWALK_VERSION-$TARGET.exe"
          fi
          BINWALK_BIN_HASH_PATH="$BINWALK_BIN_PATH.sha256.txt"
          
          cp -f "$OLD_BINWALK_BIN_PATH" "$BINWALK_BIN_PATH"
          ls -alh "$BINWALK_BIN_PATH"
          ldd "$BINWALK_BIN_PATH" || true
          "$BINWALK_BIN_PATH" -V || true

          cd "$(dirname "$BINWALK_BIN_PATH")"
          sha256sum --tag "$(basename "$BINWALK_BIN_PATH")" | tee "$BINWALK_BIN_HASH_PATH"
          
          echo "BINWALK_BIN_PATH=$BINWALK_BIN_PATH" >> $GITHUB_ENV
          echo "BINWALK_BIN_HASH_PATH=$BINWALK_BIN_HASH_PATH" >> $GITHUB_ENV


      - name: List binwalk options + signatures/extractors 
        run: |
          "$BINWALK_BIN_PATH" -h || true
          "$BINWALK_BIN_PATH" -L || true

      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.TARGET }}
          path: |
            ${{ env.BINWALK_BIN_PATH }}
            ${{ env.BINWALK_BIN_HASH_PATH }}

##############

  deploy_release:
    needs: [checkout, build]
    runs-on: ubuntu-latest
    env:
       BINWALK_CURRENT_COMMIT_ID: ${{ needs.checkout.outputs.BINWALK_CURRENT_COMMIT_ID }}
       BINWALK_VERSION: ${{ needs.checkout.outputs.BINWALK_VERSION }}
    
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v8
       with:
        pattern: binary-*
        merge-multiple: true
        path: /tmp/results

     - name: List target
       run: |
          cd "/tmp/results"
          ls -alh
  
          RELEASE_NOTES="/tmp/release_notes.txt"
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          
          cat *.sha256.txt > "$RELEASE_NOTES"
          mkdir -p "/tmp/hashes"
          mv -f *.sha256.txt "/tmp/hashes/"
  
     - name: Create a new Github release
       uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b #v3.0.1
       with:
         make_latest: true
         body_path: ${{ env.RELEASE_NOTES }}
         name: version ${{ env.BINWALK_VERSION }} - build ${{ env.BINWALK_CURRENT_COMMIT_ID }}
         tag_name: ${{ env.BINWALK_CURRENT_COMMIT_ID }}
         files: |
           /tmp/results/${{ env.BINWALK_BIN_NAME }}-*
